---
language: bash
os: linux
  - dist: xenial
sudo: required

before_install:
  - sudo apt-get install -y default-jre-headless wget
  - mkdir test; cd test
  - wget "https://raw.githubusercontent.com/apcera/sample-apps/master/example-java-jar-hello/hello.jar"

script: 
  - "bash systemd4jar.sh test/hello.jar"
  - "systemctl start jar-hello"
  - "systemctl status jar-hello"
  - "journalctl -f -n 10 -u jar-hello"
